name = "github-stats"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "5a6b7584ef0f4bdb80ec2a542d568f2f"

# Secrets (set via CLI, not stored here):
# wrangler secret put GITHUB_TOKEN
# wrangler secret put CACHE_BUST_TOKEN

[vars]
# Public vars (non-sensitive) can go here
